App\Entity\CustomerPersonalData:
  user: 'this.getUser()'
  groups:
    default:
      fields: ['street', 'zip', 'city', 'phoneNumber']
      source: 'this.getSource()'
      policy: "QOne\\PrivacyBundle\\Policy\\NullPolicy"
      transformer: ~
      conditions:
        - condition: QOne\PrivacyBundle\Condition\ObsoleteAfter
          properties:
            interval: PT2S
            message: 'Obsoleted after 2 seconds'

App\Entity\CustomerFinanceData:
  user: 'this.getUser()'
  groups:
    default:
      fields: ['income', 'expenses', 'taxBurden', 'comment']
      source: 'this.getSource()'
      policy: "QOne\\PrivacyBundle\\Policy\\RemovePolicy"
      transformer: ~
      conditions:
        - condition: QOne\PrivacyBundle\Condition\ObsoleteAfter
          properties:
            interval: PT2S
            message: 'Obsoleted after 2 seconds'