App\Entity\CustomerFinanceData:
  user: 'this.getUser()'
  groups:
    default:
      fields: ['income', 'expenses', 'tax_burden', 'comment']
      source: ~
      policy: "QOne\\PrivacyBundle\\Policy\\NullPolicy"
      transformer: ~
      conditions:
        - condition: QOne\PrivacyBundle\Condition\ObsoleteAfter
          properties:
            interval: PT2M
            message: 'Obsoleted after 2 minutes'

App\Entity\CustomerPersonalData:
  user: 'this.getUser()'
  groups:
    default:
      fields: ['street', 'zip', 'city', 'phoneNumber']
      source: ~
      policy: "QOne\\PrivacyBundle\\Policy\\NullPolicy"
      transformer: ~
      conditions:
        - condition: QOne\PrivacyBundle\Condition\ObsoleteAfter
          properties:
            interval: PT2M
            message: 'Obsoleted after 2 minutes'